/**
 * Helper to format date in local timezone as YYYYMMDDTHHmmss (no dashes, no Z)
 */
function formatLocalTime(date: Date): string {
  const Y = date.getFullYear();
  const M = String(date.getMonth() + 1).padStart(2, '0');
  const D = String(date.getDate()).padStart(2, '0');
  const H = String(date.getHours()).padStart(2, '0');
  const Min = String(date.getMinutes()).padStart(2, '0');
  const S = String(date.getSeconds()).padStart(2, '0');
  return `${Y}${M}${D}T${H}${Min}${S}`;
}

/**
 * Helper to format date in UTC as YYYYMMDDTHHmmssZ
 */
function formatUTCTime(date: Date): string {
  const Y = date.getUTCFullYear();
  const M = String(date.getUTCMonth() + 1).padStart(2, '0');
  const D = String(date.getUTCDate()).padStart(2, '0');
  const H = String(date.getUTCHours()).padStart(2, '0');
  const Min = String(date.getUTCMinutes()).padStart(2, '0');
  const S = String(date.getUTCSeconds()).padStart(2, '0');
  return `${Y}${M}${D}T${H}${Min}${S}Z`;
}

/**
 * Builds a Google Calendar "Add Event" URL template
 */
export function buildGoogleCalendarUrl(
  title: string,
  startDate: Date,
  durationMinutes: number
): string {
  const endDate = new Date(startDate.getTime() + durationMinutes * 60000);
  const formattedStart = formatLocalTime(startDate);
  const formattedEnd = formatLocalTime(endDate);

  return `https://calendar.google.com/calendar/r/eventedit?text=${encodeURIComponent(
    title
  )}&dates=${formattedStart}/${formattedEnd}&details=${encodeURIComponent(
    'Generated by Last-Minute Life Saver AI'
  )}&sf=true&output=xml`;
}

/**
 * Generates a valid iCalendar (.ics) string contents
 */
export function buildICSContent(
  tasks: Array<{ text: string; startTime: Date; duration: number }>
): string {
  const nowFormatted = formatUTCTime(new Date());
  let icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Last-Minute Life Saver AI//NONSGML v1.0//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ];

  tasks.forEach((task) => {
    const startFormatted = formatUTCTime(task.startTime);
    const endFormatted = formatUTCTime(new Date(task.startTime.getTime() + task.duration * 60000));
    const uid = `${Math.random().toString(36).slice(2)}@lifesaver`;

    icsLines.push(
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${nowFormatted}`,
      `DTSTART:${startFormatted}`,
      `DTEND:${endFormatted}`,
      `SUMMARY:${task.text.replace(/[,;]/g, '\\$&')}`,
      `DESCRIPTION:${'Generated by Last-Minute Life Saver AI'}`,
      'END:VEVENT'
    );
  });

  icsLines.push('END:VCALENDAR');
  return icsLines.join('\r\n');
}

/**
 * Triggers a download of the iCalendar content in the client browser
 */
export function downloadICS(content: string): void {
  try {
    const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'my-plan.ics';
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to trigger download for .ics file', error);
  }
}
